version: '2'
services:
  master:
    image: 'jenkins:latest'
    ports:
      - '8080:8080'
      - '50000:50000'
    volumes:
      - '/opt/jenkins/master/data:/var/jenkins_home'
      - '/var/run/docker.sock:/var/run/docker.sock'
    links:
      - 'php-slave:php-slave'
  php-slave:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
  